use crate::error::{ZfsError, ZfsResult};
use std::fs;
use std::path::Path;

/// Configure ZFS cache file for better performance
pub fn configure_zfs_cache(pool_name: &str) -> ZfsResult<()> {
    let cache_dir = "/etc/zfs/zfs-cache.d";
    let cache_file = format!("{}/{}.cache", cache_dir, pool_name);

    // Ensure cache directory exists
    if !Path::new(cache_dir).exists() {
        fs::create_dir_all(cache_dir)
            .map_err(|e| ZfsError::Config(format!("Failed to create cache directory: {}", e)))?;
    }

    // Create cache file configuration
    let cache_content = format!(
        r#"# ZFS cache configuration for pool: {}
# Auto-generated by drbd-ha
pool: {}
"#,
        pool_name, pool_name
    );

    fs::write(&cache_file, cache_content)
        .map_err(|e| ZfsError::Config(format!("Failed to write cache file: {}", e)))?;

    tracing::info!("Created ZFS cache file: {}", cache_file);
    Ok(())
}

/// Remove ZFS cache file for a pool
pub fn remove_zfs_cache(pool_name: &str) -> ZfsResult<()> {
    let cache_file = format!("/etc/zfs/zfs-cache.d/{}.cache", pool_name);

    if Path::new(&cache_file).exists() {
        fs::remove_file(&cache_file)
            .map_err(|e| ZfsError::Config(format!("Failed to remove cache file: {}", e)))?;
        tracing::info!("Removed ZFS cache file: {}", cache_file);
    }

    Ok(())
}
