//! Systemd Service Override Generator
//!
//! This module generates systemd drop-in configuration files (overrides) for services
//! managed by drbd-reactor. These overrides ensure that services properly depend on
//! their DRBD mount points and don't start before the filesystem is available.

use crate::core::run_shell_command;
use crate::error::{AppError, AppResult};

/// Generator for systemd service override (drop-in) files
pub struct ServiceOverrideGenerator;

impl ServiceOverrideGenerator {
    /// Generate a systemd service override for HA-managed services
    ///
    /// Creates a drop-in configuration file that:
    /// - Adds `BindsTo=` dependency on the mount unit (service stops if mount fails)
    /// - Adds `After=` ordering to ensure mount is ready before service starts
    /// - Disables `DefaultDependencies` to prevent unwanted automatic startup
    ///
    /// # Arguments
    /// * `service_name` - Name of the service (e.g., "mysql.service")
    /// * `mount_unit` - Name of the mount unit to depend on (e.g., "var-lib-mysql.mount")
    /// * `profile_name` - Name of the HA profile (for documentation)
    ///
    /// # Returns
    /// * `ServiceOverrideInfo` containing paths to generated files
    ///
    /// # Example
    /// ```ignore
    /// let info = ServiceOverrideGenerator::generate(
    ///     "mysql.service",
    ///     "var-lib-mysql.mount",
    ///     "mysql-ha"
    /// ).await?;
    /// // Creates /etc/systemd/system/mysql.service.d/ha-override.conf
    /// ```
    pub async fn generate(
        service_name: &str,
        mount_unit: &str,
        profile_name: &str,
    ) -> AppResult<ServiceOverrideInfo> {
        // Validate service name
        if !service_name.ends_with(".service") {
            return Err(AppError::Validation(format!(
                "Service name must end with .service: {}",
                service_name
            )));
        }

        // 1. Create override directory
        let override_dir = format!("/etc/systemd/system/{}.d", service_name);
        tokio::fs::create_dir_all(&override_dir)
            .await
            .map_err(|e| {
                AppError::Config(format!(
                    "Failed to create override directory {}: {}",
                    override_dir, e
                ))
            })?;

        // 2. Render override content
        let content = Self::render_override(mount_unit, profile_name);

        // 3. Write override file
        let override_path = format!("{}/ha-override.conf", override_dir);
        tokio::fs::write(&override_path, &content)
            .await
            .map_err(|e| {
                AppError::Config(format!(
                    "Failed to write override file {}: {}",
                    override_path, e
                ))
            })?;

        tracing::info!(
            "Generated service override for {} (mount: {}, profile: {})",
            service_name,
            mount_unit,
            profile_name
        );

        Ok(ServiceOverrideInfo {
            service_name: service_name.to_string(),
            override_dir,
            override_path,
            mount_unit: mount_unit.to_string(),
        })
    }

    /// Generate override for multiple services at once
    ///
    /// # Arguments
    /// * `services` - List of service names
    /// * `mount_unit` - Mount unit name they all depend on
    /// * `profile_name` - HA profile name
    pub async fn generate_for_services(
        services: &[String],
        mount_unit: &str,
        profile_name: &str,
    ) -> AppResult<Vec<ServiceOverrideInfo>> {
        let mut results = Vec::with_capacity(services.len());

        for service in services {
            let info = Self::generate(service, mount_unit, profile_name).await?;
            results.push(info);
        }

        Ok(results)
    }

    /// Render the override configuration content
    fn render_override(mount_unit: &str, profile_name: &str) -> String {
        format!(
            r#"# Auto-generated by drbd-ha
# HA Profile: {profile}
# DO NOT EDIT - Changes will be overwritten

[Unit]
# Dependency on the mount unit
Requires={mount}
# Ensure start after mount is ready
After={mount}
"#,
            profile = profile_name,
            mount = mount_unit,
        )
    }

    /// Remove service override for a specific service
    pub async fn remove(service_name: &str) -> AppResult<()> {
        // 1. Remove persistent override in /etc
        let override_dir = format!("/etc/systemd/system/{}.d", service_name);
        let override_path = format!("{}/ha-override.conf", override_dir);

        tracing::info!(
            "Removing service override for {}: {}",
            service_name,
            override_path
        );

        if std::path::Path::new(&override_path).exists() {
            if let Err(e) = tokio::fs::remove_file(&override_path).await {
                tracing::warn!("Failed to remove override file {}: {}", override_path, e);
                let _ =
                    run_shell_command(&format!("rm -f {}", override_path), "Force remove override")
                        .await;
            } else {
                tracing::info!("Successfully removed override file: {}", override_path);
            }
        } else {
            tracing::info!("Override file does not exist: {}", override_path);
        }

        if std::path::Path::new(&override_dir).exists() {
            if let Err(e) = tokio::fs::remove_dir(&override_dir).await {
                tracing::debug!(
                    "Could not remove directory {} (might not be empty): {}",
                    override_dir,
                    e
                );
            } else {
                tracing::info!("Removed empty override directory: {}", override_dir);
            }
        }

        // 2. Remove runtime override in /run (created by drbd-reactor)
        let run_override_dir = format!("/run/systemd/system/{}.d", service_name);
        let run_override_path = format!("{}/reactor.conf", run_override_dir);

        if std::path::Path::new(&run_override_path).exists() {
            tracing::info!("Removing runtime reactor override: {}", run_override_path);
            if let Err(e) = tokio::fs::remove_file(&run_override_path).await {
                tracing::warn!(
                    "Failed to remove reactor override {}: {}",
                    run_override_path,
                    e
                );
                let _ = run_shell_command(
                    &format!("rm -f {}", run_override_path),
                    "Force remove reactor override",
                )
                .await;
            }
        }

        if std::path::Path::new(&run_override_dir).exists() {
            let _ = tokio::fs::remove_dir(&run_override_dir).await;
        }

        Ok(())
    }

    /// Remove overrides for multiple services
    pub async fn remove_for_services(services: &[String]) -> AppResult<()> {
        for service in services {
            Self::remove(service).await?;
        }
        Ok(())
    }

    /// Check if an override exists for a service
    pub async fn exists(service_name: &str) -> bool {
        let override_path = format!("/etc/systemd/system/{}.d/ha-override.conf", service_name);
        tokio::fs::metadata(&override_path).await.is_ok()
    }

    /// Get the override file path for a service
    pub fn get_override_path(service_name: &str) -> String {
        format!("/etc/systemd/system/{}.d/ha-override.conf", service_name)
    }
}

/// Information about a generated service override
#[derive(Debug, Clone)]
pub struct ServiceOverrideInfo {
    /// Service name (e.g., "mysql.service")
    pub service_name: String,

    /// Override directory path (e.g., "/etc/systemd/system/mysql.service.d")
    pub override_dir: String,

    /// Override file path (e.g., "/etc/systemd/system/mysql.service.d/ha-override.conf")
    pub override_path: String,

    /// Mount unit this service depends on
    pub mount_unit: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_render_override() {
        let content = ServiceOverrideGenerator::render_override("var-lib-mysql.mount", "mysql-ha");

        assert!(content.contains("Requires=var-lib-mysql.mount"));
        assert!(content.contains("After=var-lib-mysql.mount"));
        assert!(!content.contains("DefaultDependencies=no"));
        assert!(content.contains("HA Profile: mysql-ha"));
    }

    #[test]
    fn test_get_override_path() {
        assert_eq!(
            ServiceOverrideGenerator::get_override_path("mysql.service"),
            "/etc/systemd/system/mysql.service.d/ha-override.conf"
        );
    }
}
