//! DRBD configuration file generator
//!
//! Generates DRBD resource configuration files.

use crate::error::{DrbdError, DrbdResult};
use serde::Serialize;
use std::collections::HashMap;
use tera::{Context, Tera};

/// Node configuration for DRBD resource
#[derive(Debug, Clone, Serialize)]
pub struct NodeConfig {
    pub hostname: String,
    pub ip: String,
    pub disk: String,
    pub node_id: u32,
}

/// DRBD resource configuration
#[derive(Debug, Clone, Serialize)]
pub struct ResourceConfig {
    pub name: String,
    pub port: u16,
    pub minor: u32,
    pub device: String,
    pub nodes: Vec<NodeConfig>,
    pub disk_options: HashMap<String, String>,
    pub net_options: HashMap<String, String>,
    /// Whether to enable auto-promote (set to false for drbd-reactor managed resources)
    pub auto_promote: bool,
}

impl Default for ResourceConfig {
    fn default() -> Self {
        let mut disk_options = HashMap::new();
        disk_options.insert("on-io-error".to_string(), "detach".to_string());

        let mut net_options = HashMap::new();
        net_options.insert("protocol".to_string(), "C".to_string());
        net_options.insert("verify-alg".to_string(), "sha256".to_string());

        Self {
            name: String::new(),
            port: 7789,
            minor: 0,
            device: "/dev/drbd0".to_string(),
            nodes: Vec::new(),
            disk_options,
            net_options,
            auto_promote: true, // Default to true, set to false for drbd-reactor managed resources
        }
    }
}

/// Configuration generator using Tera templates
pub struct ConfigGenerator {
    tera: Tera,
}

impl ConfigGenerator {
    /// Create a new configuration generator
    pub fn new() -> DrbdResult<Self> {
        let mut tera = Tera::default();

        // Add DRBD resource template
        tera.add_raw_template("drbd_resource.res", DRBD_RESOURCE_TEMPLATE)
            .map_err(|e| DrbdError::ConfigError(e.to_string()))?;

        Ok(Self { tera })
    }

    /// Generate DRBD resource configuration file content
    pub fn generate_drbd_resource(&self, config: &ResourceConfig) -> DrbdResult<String> {
        let mut context = Context::new();
        context.insert("resource", config);

        self.tera
            .render("drbd_resource.res", &context)
            .map_err(|e| DrbdError::ConfigError(e.to_string()))
    }
}

impl Default for ConfigGenerator {
    fn default() -> Self {
        Self::new().expect("Failed to create config generator")
    }
}

/// DRBD resource configuration template
const DRBD_RESOURCE_TEMPLATE: &str = r#"# DRBD resource configuration
# Generated by drbd-ha

resource {{ resource.name }} {
    options {
        auto-promote {% if resource.auto_promote %}yes{% else %}no{% endif %};
        quorum majority;
        on-no-quorum io-error;
{% if not resource.auto_promote %}
        on-suspended-primary-outdated force-secondary;
        on-no-data-accessible io-error;
{% endif %}
    }

    disk {
{% for key, value in resource.disk_options %}
        {{ key }} {{ value }};
{% endfor %}
    }

    net {
{% for key, value in resource.net_options %}
        {{ key }} {{ value }};
{% endfor %}
    }

{% for node in resource.nodes %}
    on {{ node.hostname }} {
        node-id {{ node.node_id }};
        address {{ node.ip }}:{{ resource.port }};
        volume 0 {
            device {{ resource.device }} minor {{ resource.minor }};
            disk {{ node.disk }};
            meta-disk internal;
        }
    }

{% endfor %}
    connection-mesh {
        hosts{% for node in resource.nodes %} {{ node.hostname }}{% endfor %};
    }
}
"#;

/// Paths for DRBD configuration files
pub struct ConfigPaths;

impl ConfigPaths {
    /// DRBD resource configuration directory
    pub const DRBD_CONF_DIR: &'static str = "/etc/drbd.d";

    /// Get path for DRBD resource file
    pub fn drbd_resource_path(resource_name: &str) -> String {
        format!("{}/{}.res", Self::DRBD_CONF_DIR, resource_name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_drbd_resource() {
        let gen = ConfigGenerator::new().unwrap();

        let config = ResourceConfig {
            name: "r0".to_string(),
            port: 7789,
            minor: 0,
            device: "/dev/drbd0".to_string(),
            nodes: vec![
                NodeConfig {
                    hostname: "node1".to_string(),
                    ip: "192.168.1.1".to_string(),
                    disk: "/dev/sdb1".to_string(),
                    node_id: 0,
                },
                NodeConfig {
                    hostname: "node2".to_string(),
                    ip: "192.168.1.2".to_string(),
                    disk: "/dev/sdb1".to_string(),
                    node_id: 1,
                },
            ],
            ..Default::default()
        };

        let output = gen.generate_drbd_resource(&config).unwrap();
        assert!(output.contains("resource r0"));
        assert!(output.contains("on node1"));
        assert!(output.contains("on node2"));
        assert!(output.contains("address 192.168.1.1:7789"));
        assert!(output.contains("connection-mesh"));
        assert!(output.contains("auto-promote yes"));
    }

    #[test]
    fn test_generate_drbd_resource_no_auto_promote() {
        let gen = ConfigGenerator::new().unwrap();

        let config = ResourceConfig {
            name: "r0".to_string(),
            port: 7789,
            minor: 0,
            device: "/dev/drbd0".to_string(),
            nodes: vec![NodeConfig {
                hostname: "node1".to_string(),
                ip: "192.168.1.1".to_string(),
                disk: "/dev/sdb1".to_string(),
                node_id: 0,
            }],
            auto_promote: false, // For drbd-reactor managed resources
            ..Default::default()
        };

        let output = gen.generate_drbd_resource(&config).unwrap();
        assert!(output.contains("auto-promote no"));
        // HA resources should have additional options
        assert!(output.contains("on-suspended-primary-outdated force-secondary"));
        assert!(output.contains("on-no-data-accessible io-error"));
    }

    #[test]
    fn test_config_paths() {
        assert_eq!(ConfigPaths::drbd_resource_path("r0"), "/etc/drbd.d/r0.res");
    }
}
